CREATE DATABASE IF NOT EXISTS FISHSHOP CHARACTER SET utf32;
CREATE USER IF NOT EXISTS 'user'@'localhost' IDENTIFIED BY 'password';
GRANT INSERT, SELECT, DELETE ON `FISHSHOP`.* TO 'user'@'localhost';

DROP SCHEMA IF EXISTS FISHSHOP;
CREATE SCHEMA FISHSHOP;

USE FISHSHOP;

CREATE TABLE USERS
(
    USER_ID INT PRIMARY KEY NOT NULL auto_increment,
	USERNAME VARCHAR(500) NOT NULL,
	EMAIL VARCHAR(500) NOT NULL,
	PASSWORD VARCHAR(500) NOT NULL
);

INSERT INTO USERS VALUES(1, 'admin', 'admin@admin.com', 'admin');
INSERT INTO USERS VALUES(2, 'teo', 'supergo@live.it', 'teo');

CREATE TABLE FISHES
(
    FISH_ID INT PRIMARY KEY NOT NULL auto_increment,
	NAME VARCHAR(500) NOT NULL,
	PRICE DOUBLE NOT NULL,
	WEIGHT DOUBLE,
	LENGTH DOUBLE,
	SEA VARCHAR(500),
	DESCRIPTION VARCHAR(500) NOT NULL
);

INSERT INTO FISHES VALUES (1, 'Tuna', 20.30, 40.7, 10.4, 'Mar Adriatico', 'Bel pesce, ottimo per il sushi e per fare la pasta!');

CREATE TABLE CART
(
    USER INT NOT NULL REFERENCES USERS(USER_ID),
    FISH INT NOT NULL REFERENCES FISHES(FISH_ID),
    QUANTITY INT NOT NULL,
    PRIMARY KEY (USER, FISH)
);

INSERT INTO CART VALUES (2, 1, 3);

CREATE TABLE WISHLIST
(
    USER INT NOT NULL REFERENCES USERS(USER_ID),
    FISH INT NOT NULL REFERENCES FISHES(FISH_ID),
    PRIMARY KEY (USER, FISH)
);

INSERT INTO WISHLIST VALUES (1, 1);
